In [ ]:
%tensorflow_version 2.x 
import tensorflow as tf
import numpy as np
tf.__version__

'2.8.2'

# Create 

In [ ]:
a = tf.zeros((3, 3))
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
b = tf.ones((3, 3))
b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

Create tensor with the same shape

In [ ]:
c = tf.ones_like(a)
c

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
d = tf.zeros_like(a)
d

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
e = tf.eye(3)
e

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
f = tf.eye(3, 5)
f

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)>

In [ ]:
f = tf.fill((2, 3), -5)
f

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-5, -5, -5],
       [-5, -5, -5]], dtype=int32)>

In [ ]:
g = tf.range(1, 11, 0.2)
g

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([ 1.       ,  1.2      ,  1.4000001,  1.6000001,  1.8000002,
        2.0000002,  2.2000003,  2.4000003,  2.6000004,  2.8000004,
        3.0000005,  3.2000005,  3.4000006,  3.6000006,  3.8000007,
        4.0000005,  4.2000003,  4.4      ,  4.6      ,  4.7999997,
        4.9999995,  5.1999993,  5.399999 ,  5.599999 ,  5.7999988,
        5.9999986,  6.1999984,  6.399998 ,  6.599998 ,  6.799998 ,
        6.9999976,  7.1999974,  7.399997 ,  7.599997 ,  7.799997 ,
        7.9999967,  8.199997 ,  8.399997 ,  8.599997 ,  8.799996 ,
        8.999996 ,  9.199996 ,  9.399996 ,  9.599996 ,  9.799995 ,
        9.999995 , 10.199995 , 10.399995 , 10.599995 , 10.799994 ],
      dtype=float32)>

# Random

In [ ]:
a = tf.random.normal((2, 3), mean=0, stddev=0.1)
a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.04926638,  0.02874658,  0.07004469],
       [ 0.06068921, -0.02782743,  0.07385001]], dtype=float32)>

In [ ]:
b = tf.random.uniform((2, 2), -5, 5)
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 4.356818  , -4.5641336 ],
       [ 3.3313446 ,  0.29968834]], dtype=float32)>

In [ ]:
c = tf.random.truncated_normal((3, 3), 0, 2)
c

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 2.0235796 ,  0.8633627 , -0.7594872 ],
       [-1.2381799 , -0.29142538, -1.2195255 ],
       [ 1.1054938 , -0.41217932,  0.58252263]], dtype=float32)>

In [ ]:
tf.random.set_seed(1)

# Operations

In [ ]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

In [ ]:
tf.add(a, b)
a + b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [ ]:
tf.subtract(a, b)
a - b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3], dtype=int32)>

In [ ]:
tf.divide(a, b)
a / b

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

In [ ]:
tf.multiply(a, b)
a * b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18], dtype=int32)>

In [ ]:
a ** 2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [ ]:
tf.tensordot(a, b, axes=1) # Scalar

<tf.Tensor: shape=(), dtype=int32, numpy=32>

In [ ]:
tf.tensordot(a, b, axes=0) # Matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]], dtype=int32)>

In [ ]:
a2 = tf.constant(tf.range(1, 10), shape=(3, 3))
b2 = tf.constant(tf.range(5, 14), shape=(3, 3))

tf.matmul(a2, b2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]], dtype=int32)>

In [ ]:
a2 @ b2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]], dtype=int32)>

In [ ]:
m = tf.tensordot(a, b, axes=0)
m

TypeError: ignored

In [ ]:
tf.reduce_sum(m)

<tf.Tensor: shape=(), dtype=int32, numpy=90>

In [ ]:
tf.reduce_sum(m, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([15, 30, 45], dtype=int32)>

In [ ]:
tf.reduce_sum(m, axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([24, 30, 36], dtype=int32)>

In [ ]:
tf.reduce_mean(m)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
tf.reduce_max(m)

<tf.Tensor: shape=(), dtype=int32, numpy=18>

In [ ]:
tf.reduce_prod(m)

<tf.Tensor: shape=(), dtype=int32, numpy=373248000>

In [ ]:
tf.sqrt(tf.cast(a, dtype=tf.float32))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.       , 1.4142135, 1.7320508], dtype=float32)>