<a href="https://colab.research.google.com/github/Felecort/TF-Rush/blob/master/src/9_Sequential.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x
from tensorflow import keras
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dense, Input
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
tf.__version__

'2.8.2'

# Keras is already has layers tempalates



In [2]:
model = keras.Sequential([
                          Dense(128, activation="relu"),
                          Dense(10, activation="softmax")
])
model.pop() # Delete last layer
model.add(Dense(8, activation="linear")) # Add new layer
print(model.layers)


[<keras.layers.core.dense.Dense object at 0x7f92da8a1d90>, <keras.layers.core.dense.Dense object at 0x7f935b7b0c10>]


In [3]:
model = keras.Sequential()
model.add(Dense(128, activation="relu", name="layer1"))
model.add(Dense(10, activation="softmax", name="layer2"))


## We have access to the layers params

In [4]:
print(model.layers[0].weights)


[]


In [5]:
x = tf.random.uniform((1, 20), 0, 1)
y = model(x)

print(model.layers[0].weights)

[<tf.Variable 'layer1/kernel:0' shape=(20, 128) dtype=float32, numpy=
array([[-0.03030646, -0.04787664, -0.16864233, ..., -0.05429168,
        -0.0649123 , -0.12733528],
       [ 0.10868219,  0.03444125,  0.10151312, ...,  0.02209111,
        -0.07614276,  0.19156018],
       [-0.12960789,  0.11035329,  0.07582286, ...,  0.15606007,
         0.12079194,  0.14710584],
       ...,
       [-0.14163247,  0.01032607,  0.12024012, ...,  0.12710217,
         0.0968326 ,  0.01928815],
       [-0.06877434, -0.05968075,  0.03002514, ..., -0.13473335,
         0.081655  ,  0.03290351],
       [-0.07068157, -0.01534009, -0.12617418, ..., -0.11438517,
         0.03620125, -0.194934  ]], dtype=float32)>, <tf.Variable 'layer1/bias:0' shape=(128,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 

In [6]:
print(model.weights)

[<tf.Variable 'layer1/kernel:0' shape=(20, 128) dtype=float32, numpy=
array([[-0.03030646, -0.04787664, -0.16864233, ..., -0.05429168,
        -0.0649123 , -0.12733528],
       [ 0.10868219,  0.03444125,  0.10151312, ...,  0.02209111,
        -0.07614276,  0.19156018],
       [-0.12960789,  0.11035329,  0.07582286, ...,  0.15606007,
         0.12079194,  0.14710584],
       ...,
       [-0.14163247,  0.01032607,  0.12024012, ...,  0.12710217,
         0.0968326 ,  0.01928815],
       [-0.06877434, -0.05968075,  0.03002514, ..., -0.13473335,
         0.081655  ,  0.03290351],
       [-0.07068157, -0.01534009, -0.12617418, ..., -0.11438517,
         0.03620125, -0.194934  ]], dtype=float32)>, <tf.Variable 'layer1/bias:0' shape=(128,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 

In [7]:
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (1, 128)                  2688      
                                                                 
 layer2 (Dense)              (1, 10)                   1290      
                                                                 
Total params: 3,978
Trainable params: 3,978
Non-trainable params: 0
_________________________________________________________________
None


# Supportive layers

Immideately initialize and determinate weights, weights shape respectively

Input data: [batch size; input shape]

In [12]:

model = keras.Sequential([
                          Input(shape=(784, )), # Equal to 
                          # Dense(128, activation="relu", input_shape=(784, )),
                          Dense(128, activation="relu", name="hidden1"),
                          Dense(10, activation="softmax", name="output")
])

print(model.weights)

[<tf.Variable 'hidden1/kernel:0' shape=(784, 128) dtype=float32, numpy=
array([[-0.00122373,  0.02327436, -0.07188292, ..., -0.05772682,
         0.06942188, -0.05566125],
       [-0.02977773,  0.00383233, -0.00581097, ...,  0.07494224,
        -0.03985264,  0.01526713],
       [-0.04757547, -0.07194594, -0.00269969, ...,  0.03477931,
        -0.01548868,  0.04811309],
       ...,
       [ 0.06149478, -0.05570666,  0.05310268, ..., -0.05407863,
        -0.05632148,  0.00071148],
       [ 0.0729359 , -0.05247713,  0.0605242 , ...,  0.05776425,
         0.06266572, -0.00417411],
       [ 0.00259659,  0.02389017, -0.01268051, ..., -0.0780507 ,
        -0.03076033,  0.02156773]], dtype=float32)>, <tf.Variable 'hidden1/bias:0' shape=(128,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0

In [9]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train / 255
x_test = x_test / 255

x_train = tf.reshape(tf.cast(x_train, tf.float32), [-1, 28 * 28])
x_test = tf.reshape(tf.cast(x_test, tf.float32), [-1, 28 * 28])

y_train = to_categorical(y_train, 10)
y_test_cat = to_categorical(y_test, 10)

11501568/11490434 [==============================] - 0s 0us/step


In [13]:
model.compile(optimizer="Adam",
              loss="categorical_crossentropy",
              metrics=["accuracy"])

In [14]:
model.fit(x_train, y_train, batch_size=32, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2611 - accuracy: 0.9245
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1167 - accuracy: 0.9649
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0801 - accuracy: 0.9761
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0608 - accuracy: 0.9812
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0468 - accuracy: 0.9857


In [15]:
print(model.evaluate(x_test, y_test_cat))

313/313 [==============================] - 1s 4ms/step - loss: 0.0805 - accuracy: 0.9773
[0.0805450826883316, 0.9772999882698059]


# Flexible models

change configuration, but not create new model


In [18]:
# After train (already trained)
model_ex = keras.Model(inputs=model.inputs,
                       outputs=[layer.output for layer in model.layers])


In [21]:
x = tf.expand_dims(x_test[0], axis=0)
y2 = model_ex(x)
y = model(x)
print(y, y2, sep="\n\n")
# y[0] == y2[1]

tf.Tensor(
[[7.20584410e-08 5.54823354e-10 3.22896562e-06 9.06442583e-05
  3.61171271e-12 5.12357401e-09 1.67124370e-11 9.99905586e-01
  3.16309354e-07 1.12009566e-07]], shape=(1, 10), dtype=float32)

[<tf.Tensor: shape=(1, 128), dtype=float32, numpy=
array([[0.        , 0.        , 0.        , 0.        , 1.0687776 ,
        0.        , 0.        , 0.        , 0.        , 1.5133398 ,
        0.95524055, 0.        , 0.        , 0.        , 0.34267488,
        0.        , 0.        , 1.6497427 , 0.38069278, 0.        ,
        2.6364276 , 3.6302347 , 2.6473906 , 0.        , 2.7112021 ,
        0.        , 1.2923433 , 2.0802183 , 0.16394658, 0.        ,
        1.6131206 , 0.5274468 , 1.9409213 , 3.8240852 , 0.        ,
        3.1693575 , 0.41595435, 0.7495761 , 0.8528255 , 1.9411157 ,
        0.        , 0.        , 1.7412995 , 0.25368175, 1.2710446 ,
        0.42327443, 0.70280486, 1.0355598 , 0.        , 0.24885409,
        1.9035153 , 0.        , 2.1898816 , 1.182647  , 1.4052373 ,


In [22]:
model_ex.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 784)]             0         
                                                                 
 hidden1 (Dense)             (None, 128)               100480    
                                                                 
 output (Dense)              (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


# Create new model based prew model

Add new layer to model

In [23]:
model_ex = keras.Sequential([
                             model,
                             Dense(10, activation="tanh")
])

model.trainable = False
# Or model.layers[0].trainable = False...


In [26]:
model_ex.compile(optimizer="adam",
                 loss="categorical_crossentropy",
                 metrics=["accuracy"])

In [27]:
model_ex.fit(x_train, y_train, batch_size=32, epochs=3)

Epoch 1/3
1875/1875 [==============================] - 5s 2ms/step - loss: 7.3739 - accuracy: 0.1940
Epoch 2/3
1875/1875 [==============================] - 4s 2ms/step - loss: 8.0479 - accuracy: 0.1886
Epoch 3/3
1875/1875 [==============================] - 4s 2ms/step - loss: 7.3858 - accuracy: 0.2134
